name: Backstage Actions
description: "A suite of Backstage workflows"
inputs:
  backstage_url:
    description: "Backstage URL"
    required: false
  backstage_entities_repo:
    description: "Backstage Entities repository - fallback for the URL endpoint"
    required: false
  template_path:
    description: "Handlebars Template Path"
    required: false
  output_path:
    description: "Handlebars Template Output Path"
    required: false

outputs:
  output:
    description: "The output of the helper"

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: user-check
  color: purple
