name: CD
on:
  push: [main]
  workflow_dispatch:
env:
  NODE: 16
jobs:
  bundle:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - run: pnpm bundle
      - name: Commit action bundle
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: build action" | echo ""
          git push
