name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm format-check
      - run: pnpm lint
      - run: pnpm type-check
      - name: Create output directories
        run: |
          mkdir -p tmp/backstage/all
          mkdir -p tmp/backstage/scoped
          mkdir -p tmp/backstage/lifecycle
      - run: pnpm test
        env:
          BACKSTAGE_URL: ${{ secrets.BACKSTAGE_URL }}
          BACKSTAGE_ENTITIES_REPO: ${{ secrets.BACKSTAGE_ENTITIES_REPO }}
